openapi: 3.0.1
info:
  title: webAPI
  description: Website API Server
  version: 1.0.0
servers:
  - url: /api/v1
# security:
#   - bearerAuth: []
paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login
      responses:
        '200':
          description: Login successful
  /auth/logout:
    post:
      tags:
        - Authentication
      summary: Logout
      responses:
        '501':
          description: Method not implemented
  /auth/user:
    get:
      tags:
        - Authentication
      summary: Get user info
      responses:
        '501':
          description: Method not implemented
  /auth/forgotPassword:
    post:
      tags:
        - Authentication
      summary: Forgot password
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /auth/verifyOTP:
    post:
      tags:
        - Authentication
      summary: Verify OTP
      responses:
        '501':
          description: Method not implemented
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Search parameter
        - in: query
          name: keyword
          schema:
            type: string
          description: Keyword parameter
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
        - Users
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: The created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: User ID
    get:
      tags:
        - Users
      summary: Get a user by ID
      responses:
        '200':
          description: A user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
    delete:
      tags:
        - Users
      summary: Delete a user
      responses:
        '200':
          description: The deleted user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
    put:
      tags:
        - Users
      summary: Update a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: The updated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
  /faculties:
    get:
      tags:
        - Faculties
      summary: Get all faculties
      responses:
        '200':
          description: A list of faculties
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Faculty'
    post:
      tags:
        - Faculties
      summary: Create a new faculty
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Faculty'
      responses:
        '201':
          description: Faculty created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Faculty'
  /faculties/{id}:
    get:
      tags:
        - Faculties
      summary: Get a faculty by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A faculty
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Faculty'
    put:
      tags:
        - Faculties
      summary: Update a faculty
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Faculty'
      responses:
        '200':
          description: Faculty updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Faculty'
    delete:
      tags:
        - Faculties
      summary: Delete a faculty
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Faculty deleted
  /events:
    get:
      tags:
        - Events
      summary: List all events
      responses:
        '200':
          description: A list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
    post:
      tags:
        - Events
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: New event created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
  /events/{id}:
    get:
      tags:
        - Events
      summary: Get an event by ID
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: An event object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Event not found
    put:
      tags:
        - Events
      summary: Update an event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Event updated
        '404':
          description: Event not found
    delete:
      tags:
        - Events
      summary: Delete an event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Event deleted
        '404':
          description: Event not found
  /contributions:
    get:
      tags:
        - Contributions
      summary: Get all contributions
      responses:
        '200':
          description: A list of contributions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contribution'
    post:
      tags:
        - Contributions
      summary: Create a new contribution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contribution'
      responses:
        '201':
          description: Contribution created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contribution'
  /contributions/{id}:
    get:
      tags:
        - Contributions
      summary: Get a contribution by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A contribution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contribution'
    put:
      tags:
        - Contributions
      summary: Update a contribution
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contribution'
      responses:
        '200':
          description: Contribution updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contribution'
    delete:
      tags:
        - Contributions
      summary: Delete a contribution
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Contribution deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contribution'
  /comments:
    get:
      tags:
        - Comments
      summary: Get all comments
      responses:
        '200':
          description: A list of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
    post:
      tags:
        - Comments
      summary: Create a new comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '201':
          description: Comment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
  /comments/{id}:
    get:
      tags:
        - Comments
      summary: Get a comment by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
    put:
      tags:
        - Comments
      summary: Update a comment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '200':
          description: Comment updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
    delete:
      tags:
        - Comments
      summary: Delete a comment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Comment deleted
  /spec:
    get:
      tags:
        - Specification
      summary: Get the API specification
      responses:
        '200':
          description: Return the API specification
          content: {}
components:
  schemas:
    Event:
      type: object
      required:
        - Name
        - Description
        - ClosureDate
        - FinalDate
        - FacultyID
      properties:
        ID:
          type: integer
          format: int64
          nullable: true
          readOnly: true
        Name:
          type: string
        Description:
          type: string
        ClosureDate:
          type: string
          format: date-time
        FinalDate:
          type: string
          format: date-time
        CreatedAt:
          type: string
          format: date-time
          readOnly: true
        UpdatedAt:
          type: string
          format: date-time
          readOnly: true
        FacultyID:
          type: integer
          format: int64
    User:
      type: object
      properties:
        ID:
          type: integer
          format: int64
          nullable: true
        Name:
          type: string
        Password:
          type: string
        Salt:
          type: string
        Email:
          type: string
          format: email
        Phone:
          type: string
          nullable: true
        Address:
          type: string
          nullable: true
        CreatedAt:
          type: string
          format: date-time
          readOnly: true
        UpdatedAt:
          type: string
          format: date-time
          readOnly: true
        RoleID:
          type: integer
          format: int64
        FacultyID:
          type: integer
          format: int64
      required:
        - Name
        - Password
        - Email
        - UpdatedAt
        - RoleID
        - FacultyID
      title: User
    Faculty:
      type: object
      properties:
        ID:
          type: integer
          nullable: true
        Name:
          type: string
        Description:
          type: string
        IsEnabledGuest:
          type: boolean
        CreatedAt:
          type: string
          format: date-time
          readOnly: true
        UpdatedAt:
          type: string
          format: date-time
          readOnly: true
      required:
        - Name
        - Description
        - IsEnabledGuest
    Comment:
      type: object
      properties:
        ID:
          type: integer
          nullable: true
        Content:
          type: string
        CreatedAt:
          type: string
          format: date-time
          nullable: true
        UpdatedAt:
          type: string
          format: date-time
          nullable: true
        ContributionID:
          type: integer
        UserID:
          type: integer
      required:
        - Content
        - ContributionID
        - UserID
    Contribution:
      type: object
      properties:
        ID:
          type: integer
          nullable: true
        Name:
          type: string
        Content:
          type: string
        IsPublic:
          type: boolean
        IsApproved:
          type: boolean
        CreatedAt:
          type: string
          format: date-time
        UpdatedAt:
          type: string
          format: date-time
        EventID:
          type: integer
        UserID:
          type: integer
        StatusID:
          type: integer
      required:
        - Name
        - Content
        - IsPublic
        - IsApproved
        - EventID
        - UserID
        - StatusID
    Authentication:
      type: object
      properties:
        Email:
          type: string
          format: email
        Password:
          type: string
      required:
        - Email
        - string
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
