openapi: 3.0.1
info:
  title: webAPI
  description: Website API Server
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: Examples
  description: Simple example endpoints
- name: Specification
  description: The swagger API specification
paths:
  /examples:
    get:
      tags:
      - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
          content: {}
    post:
      tags:
      - Examples
      description: Create a new example
      requestBody:
        description: an example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleBody'
        required: true
      responses:
        200:
          description: Returns all examples
          content: {}
  /examples/{id}:
    get:
      tags:
      - Examples
      parameters:
      - name: id
        in: path
        description: The id of the example to retrieve
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Return the example with the specified id
          content: {}
        404:
          description: Example not found
          content: {}
  /users:
    get:
      tags:
      - Users
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
          content: {}
    post:
      tags:
      - Users
      description: Create a new example
      requestBody:
        description: an example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleBody'
        required: true
      responses:
        200:
          description: Returns all examples
          content: {}
  /users/{id}:
    get:
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: The id of the example to retrieve
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Return the example with the specified id
          content: {}
        404:
          description: Example not found
          content: {}

  /event:
    get:
      tag:
      - Event
      response:
        200:
          description: Return all Event
          content: {}
  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}

          
components:
  schemas:
    Event:
      title: Event
      required:
      - name
      - description
      - ClosureDate
      type: object
      properties:
        name:
          type: string
          example: School Marketing
        description:
          type: string
          example: An event of School Marketing
        ClosureDate:
          type: Date
          example: 2000/22/0

      
