name: Backend CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile code and Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - run: | 
        cd ./backend/webAPI
        npm i 
    - run: npm run compile --if-present
