name: Deploy Node.js to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version:  '18.x'

          
      - name: Create .env file
        run: |
          cd ./backend/webAPI
          echo "NODE_ENV=production" > .env
          echo "PORT=8080" >> .env
          echo "DATABASE_URL=\"${{ secrets.DATABASE_URL }}\"" >> .env
          echo "AZURE_STORAGE_CONNECTION_STRING=\"${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}\"" >> .env
          echo "AZURE_STORAGE_CONTAINER_NAME=\"${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}\"" >> .env
          echo "JWT_SECRET=\"${{ secrets.JWT_SECRET }}\"" >> .env
          echo "SESSION_SECRET=\"${{ secrets.SESSION_SECRET }}\"" >> .env
          echo "GOOGLE_CLIENT_SECRET=\"${{ secrets.GOOGLE_CLIENT_SECRET }}\"" >> .env
          echo "GOOGLE_CLIENT_ID=\"${{ secrets.GOOGLE_CLIENT_ID }}\"" >> .env
          echo "NOVU_API_KEY=\"${{ secrets.NOVU_API_KEY }}\"" >> .env
          echo "NOVU_IDENTIFIER=\"${{ secrets.NOVU_IDENTIFIER }}\"" >> .env
          echo "OPENAPI_SPEC=\"${{ secrets.OPENAPI_SPEC }}\"" >> .env

      - name: npm install, build, and test
        run: |
          cd ./backend/webAPI
          npm install
          npm run compile --if-present   
          

      - name: Zip artifact for deployment
        run:  |
          cd ./backend/webAPI
          zip -r ../../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cuongnd'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
