name: Deploy to VPS

on:
  push:
    branches:
      - master
  workflow_dispatch:  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: SSH into VPS and run command
        run: ssh root@${{secrets.VPSIP}}

      - name: Deploy to VPS
        run: |
          cd /usr/src/Enterprise_DevWeb/backend/webAPI
          git pull
          npm install
          npm run build
          pm2 restart all
